[[configs]]
name = "nushell"
links = [
    ["nushell", "nushell"]
]
platform = ["linux", "macos", "windows"]

[[configs]]
name = "starship"
links = [
    ["starship.toml", "starship.toml"]
]
platform = ["linux", "macos", "windows"]

[[configs]]
name = "tmux"
links = [
    ["tmux", "tmux"],
    ["tmux-powerline/themes/sasa.sh", "tmux/plugins/tmux-powerline/themes/sasa.sh"],
]
platform = ["linux", "macos"]

[[configs]]
name = "wezterm"
links = [
    ["wezterm", "wezterm"]
]
platform = ["macos"]