format = """
$os\
$username\
[](bg:#eeeeee fg:#4c7b57)\
$directory\
[](fg:#eeeeee bg:#4c7b57)\
$git_branch\
$git_status\
[](fg:#4c7b57 bg:#b5fff9)\
$conda\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#b5fff9 bg:#4c7b57)\
$docker_context\
[](fg:#4c7b57 bg:#eeeeee)\
$time\
[ ](fg:#eeeeee)
[ ❯](fg:#eeeeee) \
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#4c7b57 fg:#eeeeee bold"
style_root = "bg:#4c7b57 fg:#eeeeee bold"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#4c7b57"
disabled = true # Disabled by default

[directory]
style = "bg:#eeeeee fg:#4c7b57"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[conda]
style = "bg:#b5fff9 fg:#4c7b57"
format = '[ $symbol($environment) ]($style)'
symbol = " "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#4c7b57 fg:#eeeeee"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4c7b57 fg:#eeeeee"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#b5fff9 fg:#4c7b57"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#b5fff9 fg:#4c7b57"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#b5fff9 fg:#4c7b57"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#b5ffff fg:#4c7b57"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#b5fff9 fg:#4c7b57"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#eeeeee fg:#4c7b57"
format = '[ $time ]($style)'